spring:
  application:
    name: player-admin
  web:
    resources:
      # 映射本地HLS分片目录到 /hls/** 访问路径
      static-locations: file:F:/study/m3u8
  mvc:
    static-path-pattern: /hls/**
server:
  port: 8443 # HTTPS 默认端口
  ssl:
    key-store: classpath:springboot-https.p12 # 证书文件路径
    key-store-password: 123456 # 证书密码
    key-store-type: PKCS12